ldg/project/dogma/views/auth_views.py
from flask import Blueprint, Flask, render_template, flash, request, session, url_for, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from dogma import db
from dogma.forms import UserCreateForm, UserLoginForm
from dogma.models import User


bp = Blueprint('auth', __name__, url_prefix='/')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        userid=form.userid.data,
                        number=form.number.data,
                        )
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userid=form.userid.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.main'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

ldg/project/dogma/views/detail_views.py
from flask import Blueprint, render_template


from dogma.models import Imginfo

bp = Blueprint('detail', __name__, url_prefix='/detail')


@bp.route('/<int:imginfo_id>/', methods=['GET'])
def detail(imginfo_id):
    global imginfo
    imginfo = Imginfo.query.get(imginfo_id)
    img_path = "images/" + imginfo.imgname

    return render_template('main/detail.html', imginfo=imginfo, img_path = img_path)

ldg/project/dogma/views/main_views.py
# from werkzeug.utils import redirect

from flask import Blueprint, Flask, render_template, request, session, abort, url_for
# from keras.models import load_model
# from keras.preprocessing import image
# from keras import utils

# import numpy as np
# from datetime import datetime
# import os

from dogma.models import Imginfo
# from dogma import db

# from dogma.forms import UserCreateForm, UserLoginForm
# img_dir = os.listdir('dogma/static/images')

def login_is_required():
    if "google_id" not in session:
        session.clear()
        return False
    else:
        return True

def login_is_required2():
    if "user_id" not in session:
        session.clear()
        return False
    else:
        return True

bp = Blueprint('main', __name__, url_prefix='/main')


@bp.route('/', methods=['GET', 'POST'])
def main():
    if "google_id" in session:
        imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())
        print("@@@DEBUG2@@@", session)
        return render_template('main/main.html', imginfo_list=imginfo_list, isSession=login_is_required())
    
    elif "user_id" in session:
        imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())
        print("@@@DEBUG2@@@", session)
        return render_template('main/main.html', imginfo_list=imginfo_list, isSession=login_is_required2())

ldg/project/dogma/views/oauth_views.py
from flask import Blueprint, Flask, abort, redirect, request, session, url_for

from google_auth_oauthlib.flow import Flow
import os, pathlib
from pip._vendor import cachecontrol
import google.auth.transport.requests
from google.oauth2 import id_token
import requests

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

# 구글 Oauth 설정
GOOGLE_CLIENT_ID = "167648320999-ikubtf4huo58ib4cb0j1qfj7kqirj09c.apps.googleusercontent.com"
# client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "C:\localRepository\Bigdata_busan\ldg\project\dogma\static\client_secret.json")
client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "../static/client_secret.json")
# 서버 파일 경로
# client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "/home/ubuntu/projects/Bigdata_busan/ldg/project/dogma/static/client_secret.json")

flow = Flow.from_client_secrets_file(
    client_secrets_file=client_secrets_file,
    scopes=["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email", "openid"],
    # redirect_uri="http://127.0.0.1:5000/oauth/callback"
    redirect_uri="http://www.sixdogma.site:5000/oauth/callback"
    )

bp = Blueprint("oauth", __name__, url_prefix="/oauth")

def login_is_required(function):
    def wrapper(*args, **kwargs):
        if "google_id" not in session:
            abort(401) # Authorization required
        else:
            return function()
    return wrapper

@bp.route("/login")
def login():
    authorization_url, state = flow.authorization_url()
    session["state"] = state
    return redirect(authorization_url)

@bp.route("/callback")
def callback():
    flow.fetch_token(authorization_response=request.url)

    if not session["state"] == request.args["state"]:
        abort(500) # state does not match!

    credentials = flow.credentials
    request_session = requests.session()
    cached_session = cachecontrol.CacheControl(request_session)
    token_request = google.auth.transport.requests.Request(session=cached_session)

    id_info = id_token.verify_oauth2_token(
        id_token=credentials._id_token,
        request=token_request,
        audience=GOOGLE_CLIENT_ID,
        clock_skew_in_seconds=2
    )

    session["google_id"] = id_info.get("sub")
    session["name"] = id_info.get("name")
    print("@@@DEBUG@@@", session["csrf_token"])
    return redirect(url_for('main.main'))

@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

@bp.route("/protected_area")
@login_is_required
def protected_area():
    return "protected! <a href='/oauth/logout'><button>Logout</button></a>"

ldg/project/dogma/views/submit_views.py
from flask import Blueprint, Flask, render_template, request, session

from keras import utils
from keras.models import load_model

from dogma.models import Imginfo,Imginfo2
from dogma import db

import numpy as np
from datetime import datetime

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

engine = create_engine("apachehive:///?Server=13.125.214.72&Port=10000&TransportMode=BINARY")
factory = sessionmaker(bind=engine)
session = factory()

dic = {0: '정상', 1: '불량'}

# 기존 모델 로드
# model = load_model('dogma/static/cnn_3.h5')

# 재훈련된 모델 로드
model = load_model('dogma/static/cnn_padding.h5')

model.make_predict_function()

now = datetime.now()

def predict_label(img_path):
    test_img = utils.load_img(img_path, color_mode='grayscale', target_size=(256, 256), interpolation='bilinear')
    x = utils.img_to_array(test_img)
    x = np.expand_dims(x, axis=0)
    images = np.vstack([x])

    p = model.predict(images, batch_size=16)

    tmp = p.tolist()
    return dic[tmp[0][0]]

def login_is_required():
    if "google_id" not in session:
        session.clear()
        return False
    else:
        return True

def login_is_required2():
    if "user_id" not in session:
        session.clear()
        return False
    else:
        return True

bp = Blueprint('submit', __name__, url_prefix='/main')

@bp.route('/submit/', methods=['GET', 'POST'], strict_slashes=False)
def predict():
    if "google_id" in session:
        if request.method == 'POST':
            global pred, img_path, img_path_name

            try:
                img = request.files['my_image']
                img_path_name = 'images/' + img.filename
                new_file_name = "img_" + datetime.now().strftime("%y.%m.%d-%H：%M：%S.%f") + '_' + img.filename
                img_path = "dogma/static/images/" + new_file_name
                img.save(img_path)

                pred = predict_label(img_path)

                if pred == "정상":
                    img.save("dogma/static/images/good/" + new_file_name)
                else:
                    img.save("dogma/static/images/bad/" + new_file_name)
                render_img_path = 'images/' + new_file_name

                # img_info = Imginfo(imgname=new_file_name, predictdate=now, prediction=pred)
                
                img_info = Imginfo2(imgname=new_file_name, predictdate=now, prediction=pred)

                session.add(img_info)
                session.commit()
            
                # db.session.add(img_info)
                # db.session.commit()
                
                imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())

            # print("@@@DEBUG2@@@", session["csrf_token"])

                return render_template('main/submit.html', prediction = pred, img_path = img_path, img_name=render_img_path, imginfo_list=imginfo_list, isSession=login_is_required())
            except:
                imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())
                return render_template('main/main.html',imginfo_list=imginfo_list, isSession=login_is_required())
    elif "user_id" in session:
        if request.method == 'POST':
            try:
                img = request.files['my_image']
                img_path_name = 'images/' + img.filename
                new_file_name = "img_" + datetime.now().strftime("%y.%m.%d-%H：%M：%S.%f") + '_' + img.filename
                img_path = "dogma/static/images/" + new_file_name
                img.save(img_path)

                pred = predict_label(img_path)

                if pred == "정상":
                    img.save("dogma/static/images/good/" + new_file_name)
                else:
                    img.save("dogma/static/images/bad/" + new_file_name)
                render_img_path = 'images/' + new_file_name

                img_info = Imginfo(imgname=new_file_name, predictdate=now, prediction=pred)
                
                
                db.session.add(img_info)
                db.session.commit()
                
                imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())

                return render_template('main/submit.html', prediction = pred, img_path = img_path, img_name=render_img_path, imginfo_list=imginfo_list, isSession=login_is_required2())
            except:
                imginfo_list = Imginfo.query.order_by(Imginfo.predictdate.asc())
                return render_template('main/main.html', imginfo_list=imginfo_list, isSession=login_is_required2())

ldg/project/dogma/templates/main/detail.html
{% extends 'base.html' %}
{% block content %}
<body id="page-top">
    <!-- js 부트스트랩 코드 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                </div>
                <div class="sidebar-brand-text mx-7">SixDogma</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">

            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">

                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
            </li>
            <!-- Nav Item - Tables -->

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- 네비게이션바 Topbar -->
                {% include "navbar.html" %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800"></h1>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <!-- 모델 기능 -->
                        <div>
                            <form action="/main/submit" method="post" enctype="multipart/form-data">
                                <div class="mb-3">
                                    <div>
                                        <center>
                                        <img src= {{ url_for('static', filename= img_path) }} height="600px" width="600px"> 
                                        <p>
                                        <h2 class="h3 mb-2 text-gray-900">판정 결과 : {{ imginfo.prediction }}</h2>
                                        </center>
                                    </div>
                                </div>

                                <div>
                                </div>
                            </form>
                        </div>

                        <div class="card-body">
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Sixdogma 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    {% if g.user %}
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">로그아웃 하시겠습니까?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">취소</button>
                    <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">로그아웃</a>
                </div>
            </div>
        </div>
    </div>
    {% elif session['google_id'] %}
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">로그아웃 하시겠습니까?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">취소</button>
                    <a class="btn btn-primary" href="{{ url_for('oauth.logout') }}">로그아웃</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"></script>
    

</body>

{% endblock %}

ldg/project/dogma/templates/main/main.html
{% extends 'base.html' %}
{% block content %}
{% if not isSession %}
<!-- <meta http-equiv="refresh" content="0; url=http://127.0.0.1:5000"></meta> -->
<meta http-equiv="refresh" content="0; url= {{ url_for( 'auth.login' ) }}"></meta>
{% endif %}
<body id="page-top">
    <!-- js 부트스트랩 코드 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                </div>
                <div class="sidebar-brand-text mx-7">SixDogma</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">

            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->

            <!-- Nav Item - Charts -->
            <li class="nav-item">
            </li>
            <!-- Nav Item - Tables -->

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- 네비게이션바 Topbar -->
                {% include "navbar.html" %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <!-- 모델 기능 -->
                        <div>
                            <h2 class="h3 mb-2 text-gray-900">이미지 판독</h2>
                            <form action="/main/submit" method="post" enctype="multipart/form-data">
                                <div class="mb-3">
                                    <table>
                                        <tr>
                                            <th>
                                                <label for="pwd" class="form-label"></label>
                                            </th>
                                        </tr>
                                        <tr>
                                            <th>
                                                <input class="form-control" type="file" placeholder="Hours Studied" name="my_image" id="pwd">
                                            </th>
                                            <th class ="dogma-button">    
                                                <button class ="dogma-button" type="submit">판정</button>
                                            </th>
                                        </tr>
                                    </table>
                                </div>
                            </form>

                            {% if prediction %}
                            <center>
                                <img src= {{ url_for('static', filename= img_name) }} height="450px" width="450px">
                                <br>
                                <h1 class="h3 mb-2 text-gray-800"> 판정 결과   : {{prediction}} </h1>
                            </center>
                            {% endif %}

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>번호</th>
                                            <th>파일 이름</th>
                                            <th>판정 일시</th>
                                            <th>판정 결과</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>번호</th>
                                            <th>파일 이름</th>
                                            <th>판정 일시</th>
                                            <th>판정 결과</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% if imginfo_list %}
                                        {% for imginfo in imginfo_list %}
                                        <tr>
                                            <td>{{ loop.index }}</td>
                                            <td>
                                                <a href="/detail/{{ imginfo.id }}" target = "_ parent">{{ imginfo.imgname }}</a>
                                            </td>
                                            <td>{{ imginfo.predictdate }}</td>
                                            <td>{{ imginfo.prediction }}</td>
                                        </tr>
                                        {% endfor %}
                                        {% else%}
                                        <tr>
                                            <td>판정 결과 없음</td>
                                        </tr>
                                        {% endif %}                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Sixdogma 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    {% if g.user %}
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">로그아웃 하시겠습니까?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">취소</button>
                    <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">로그아웃</a>
                </div>
            </div>
        </div>
    </div>
    {% elif session['google_id'] %}
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">로그아웃 하시겠습니까?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">취소</button>
                    <a class="btn btn-primary" href="{{ url_for('oauth.logout') }}">로그아웃</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"></script>
    

</body>

{% endblock %}